platform :ios, '8.0'

target 'CokeStudio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImage', '~>3.8'
  # Pods for CokeStudio

  target 'CokeStudioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CokeStudioUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
